---
title: "Final project"
author: "Group 1"
date: "10/5-2021"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Description
This project does different R analysis on the heart data set:
https://archive.ics.uci.edu/ml/datasets/Heart+Disease?fbclid=IwAR3SbR6Eo3ow8dYal4mTv321XOUAUg8yw5g_WY-eDz9hUQS_0jJ0-qTR9v8

Datasets from Long Beach, Hungary, Cleveland and Switzerland are all included. Before using the data, our R script joins all the datasets and convert serum cholesterol and blood pressure values of 0 into N/A's, since these are 

Let people know what your project can do specifically. Provide context and add a link to any reference visitors might be unfamiliar with. A list of Features or a Background subsection can also be added here. If there are alternatives to your project, this is a good place to list differentiating factors.

## Data 
Attribute Information:

1. The age of the participates in the study in years    

2. The gender of the  participates

    * 0 = female

    * 1 = male

3. The type of chest pain

    * 1 = typical angina

    * 2 = atypical angina

    * 3 = non-anginal pain

    * 4 = asymptomatic

4. The resting blood pressure in mm Hg on admission to the hospital  

5. The serum cholestoral in $\frac{mg}{dl}$    

6. The fasting blood sugar

    * 0 = fasting blood sugar $< 120 \frac{mg}{dl}$

    * 1 = fasting blood sugar $> 120 \frac{mg}{dl}$

7. The result of the resting electrocardiographic

    * 0 = normal

    * 1 = ST  and/or T wave abnormality

    * 2 = showing probable or definite left ventricular hypertrophy

8. The maximum heart rate achieved   

9. Exercise induced angina

    * 1 = yes

    * 0 = no

10. ST depression induced by exercise relative to resting stage   

11. The slope of the peak exercise ST segment

    * 1 = upsloping

    * 2 = flat

    * 3 = downsloping

12. The number of major vessels colored by flourosopy

    * $0\leq Major\ vessels\leq 3$

13. The defect type of thalassemia

    * 3 = normal

    * 6 = fixed defect

    * 7 = reversable defect

14. The diagnosis of heart disease

    * 0 = no heart disease present

    * [1;4] = types of heart disease 

## Installation
In order to get the all the project files clone the following repository from git: 
git clone https://github.com/rforbiodatascience21/2021_group01_final_project

## Dependencies
The following software needs to be installed for running the code locally:
- R

For running non-local, an Rstudio Cloud session can be used: https://rstudio.cloud/

The following packages needs to be installed inside R for the scripts to function:

- library(tidyverse)
- library(ggplot2)
- library(ggpubr)
- library(broom)
- library(cowplot)
-
-



Within a particular ecosystem, there may be a common way of installing things, such as using Yarn, NuGet, or Homebrew. However, consider the possibility that whoever is reading your README is a novice and would like more guidance. Listing specific steps helps remove ambiguity and gets people to using your project as quickly as possible. If it only runs in a specific context like a particular programming language version or operating system or has dependencies that have to be installed manually, also add a Requirements subsection.

## Usage
Use examples liberally, and show the expected output if you can. It's helpful to have inline the smallest example of usage that you can demonstrate, while providing links to more sophisticated examples if they are too long to reasonably include in the README.


